### ISSUE TITLE
bleach doesn't work with html5lib==1.0b9 either

### ISSUE THREAD

**Issue by ursomniac** [mozilla/bleach#269]
same issue (cannot import name sanitizer).

Timeframe for fix?

**Comment by willkg** [comment]
That's puzzling--bleach 2.0 works fine with html5lib 1.0b9 for me.

Can you do a "pip freeze" and paste the output here?

**Comment by willkg** [comment]
Here's me installing bleach 2.0 and html5lib 1.0b9 in a fresh virtualenv:

```
~> mkvirtualenv bleach
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/willkg/.virtualenvs/bleach/bin/python2
Also creating executable in /home/willkg/.virtualenvs/bleach/bin/python
cInstalling setuptools, pkg_resources, pip, wheel...d
done.
 <bleach> ~> pip install bleach==2.0 html5lib==1.0b9
Collecting bleach==2.0
  Downloading bleach-2.0.0-py2.py3-none-any.whl
Collecting html5lib==1.0b9
  Downloading html5lib-1.0b9.tar.gz (244kB)
    100% |████████████████████████████████| 245kB 3.0MB/s 
Requirement already satisfied: six in ./.virtualenvs/bleach/lib/python2.7/site-packages (from bleach==2.0)
Collecting webencodings (from html5lib==1.0b9)
Requirement already satisfied: setuptools>=18.5 in ./.virtualenvs/bleach/lib/python2.7/site-packages (from html5lib==1.0b9)
Requirement already satisfied: appdirs>=1.4.0 in ./.virtualenvs/bleach/lib/python2.7/site-packages (from setuptools>=18.5->html5lib==1.0b9)
Requirement already satisfied: packaging>=16.8 in ./.virtualenvs/bleach/lib/python2.7/site-packages (from setuptools>=18.5->html5lib==1.0b9)
Requirement already satisfied: pyparsing in ./.virtualenvs/bleach/lib/python2.7/site-packages (from packaging>=16.8->setuptools>=18.5->html5lib==1.0b9)
Building wheels for collected packages: html5lib
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: /home/willkg/.cache/pip/wheels/44/2b/60/fce64372ad02992b7c4b724bbf6d769a5b9a861e11d6090c0e
Successfully built html5lib
Installing collected packages: webencodings, html5lib, bleach
Successfully installed bleach-2.0.0 html5lib-1.0b9 webencodings-0.5
 <bleach> ~> python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> bleach.clean('abcde')
u'abcde'
>>> 
```

**Comment by ursomniac** [comment]
OK - here's the requirements.txt file.   Yes, there are a LOT of packages involved but that's the nature of the project.   I suspect the problem is conflicting version requirements between, e.g., bleach and django-text-ckeditor.

I WAS able to get things working nicely using html5lib==0.9999999 and bleach==1.5, although there are features in 2.0.0 I'd really like to use (but I can code around that if I have to).

**Comment by willkg** [comment]
Ok. If you need help, let me know, but I don't think there's anything I can do here.
